version: 2

project_name: yakuqr

before:
  hooks:
    - go mod tidy

builds:
  - id: yakuqr
    main: ./cmd/yakuqr
    binary: yakuqr
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: yakuqr
    formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md

checksum:
  name_template: "checksums.txt"

changelog:
  disable: true

release:
  github:
    owner: gozuk16
    name: yakuqr
